[build]
  command = "npm run build"
  publish = "out" # for Next.js static export
  # or "build" if you're deploying a normal React app

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
